### ISSUE TITLE
Error in Chrome when trying to convert a specific UTF-8 sequence

### ISSUE THREAD

**Issue by smuehlst** [r12a/app-conversion#7]
How to reproduce:

- Open https://r12a.github.io/app-conversion/ in Chrome (I used 71.0.3578.80)
- Paste the following into the "UTF-8 code units" field: f4 8f bf be f4 8f b3 b9
- Click "Convert" button next to the "UTF-8 code units" field

Expected result:

UTF-8 sequence is converted successfully or error message about invalid UTF-8 sequence generated.

Actual result:

The Chrome tab crashes.

When I try the same steps in Microsoft Edge I get U+10FFFEU+10FCF9 as the result.

It is unclear to me whether this is a bug in Chrome or in app-conversion itself.

**Comment by frzsombor** [comment]
I also found that specific characters causes a Chrome tab crash.
If I paste the `💬` emoji into the first "green" field, chrome crashes if I click "Convert".

However, I also found that if I use the "[old version](https://r12a.github.io/app-conversion/index8-2)", there is no problem with my example.

*Edit: I just noticed that #6 reports a similar problem*

**Comment by smuehlst** [comment]
The original issue is no longer reproducible.
